version: '3.8'

services:
  web:
    build: ./docker
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"

  php:
    image: php:7.4-fpm
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
